/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import com.toedter.calendar.JDateChooser;
import dao.daoPersonne;
import factory.Factory;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import objet.Personne;

/**
 *
 * @author Super-Afg
 */
public class JDInsertPersonne extends javax.swing.JDialog {

    /**
     * Creates new form JDInsertPersonne
     */
    public JDInsertPersonne(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MaskFormatter mfn=null;
        try { mfn = new MaskFormatter("U??????????????????????????????????");
            mfn.setPlaceholderCharacter(' '); 
        } catch (ParseException e){  
        }
        tfNom = new JFormattedTextField (mfn);  ;
        MaskFormatter mfp=null;  try { mfp = new MaskFormatter("U??????????????????????????????????");  mfp.setPlaceholderCharacter(' ');   } catch (ParseException e){    }
        tfPrenom = new JFormattedTextField (mfp);  ;
        MaskFormatter mfTel=null;
        try { mfTel = new MaskFormatter("## ### ## ##");
            mfTel.setPlaceholderCharacter(' '); 
        } catch (ParseException e){  
        }
        tfTelephone = new JFormattedTextField (mfTel);  ;
        tfMail = new javax.swing.JTextField();
        chk_listRouge = new javax.swing.JCheckBox();
        chk_membre = new javax.swing.JCheckBox();
        chkDonateur = new javax.swing.JCheckBox();
        chkVolontaire = new javax.swing.JCheckBox();
        chk_autre_refuge = new javax.swing.JCheckBox();
        chk_refuge = new javax.swing.JCheckBox();
        chkRevendeur = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        taAdresse = new java.awt.TextArea();
        taNote = new java.awt.TextArea();
        jDateChooserDateViste = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnEnregister = new javax.swing.JButton();
        chk_home = new javax.swing.JCheckBox();
        MaskFormatter mfGsm=null;
        try { mfGsm = new MaskFormatter("#### ## ## ##");
            mfGsm.setPlaceholderCharacter(' '); 
        } catch (ParseException e){  
        }
        tfMobile = new JFormattedTextField (mfGsm);  ;
        jLabel9 = new javax.swing.JLabel();
        MaskFormatter mf=null;
        try { mf = new MaskFormatter("####");
            mf.setPlaceholderCharacter(' '); 
        } catch (ParseException e){  
        }
        tfCodePostal = new JFormattedTextField (mf);
        ;
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tfVille = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Personne");

        jLabel1.setText("Nom :");

        jLabel2.setText("Prénom :");

        jLabel3.setText("Adresse :");

        jLabel4.setText("Telephone :");

        jLabel5.setText("Mail :");

        tfTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelephoneActionPerformed(evt);
            }
        });

        chk_listRouge.setText("Liste rouge");
        chk_listRouge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_listRougeActionPerformed(evt);
            }
        });

        chk_membre.setText("Membre");

        chkDonateur.setText("Donateur");

        chkVolontaire.setText("Volontaire");

        chk_autre_refuge.setText("Autre refuge");

        chk_refuge.setText("Travail au refuge");

        chkRevendeur.setText("Revendeur");

        jLabel6.setText("Note du visite :");

        taNote.setEditable(false);

        jDateChooserDateViste.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooserDateViste.setDate(new java.util.Date(1397463750000L));
        jDateChooserDateViste.setDateFormatString("dd-MM-yyyy");
        jDateChooserDateViste.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDateVistePropertyChange(evt);
            }
        });

        jLabel7.setText("Date du visite:");

        jLabel8.setText("Visite à domicile du propriétaire :");

        btnEnregister.setText("Enregistrer");
        btnEnregister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregisterActionPerformed(evt);
            }
        });

        chk_home.setText("Reçu visite");
        chk_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_homeActionPerformed(evt);
            }
        });

        jLabel9.setText("Mobile :");

        jLabel10.setText("Code postal :");

        jLabel11.setText("Ville :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(tfMail, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(57, 57, 57)
                        .addComponent(tfVille, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(25, 25, 25)
                        .addComponent(tfTelephone))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(45, 45, 45)
                        .addComponent(tfMobile, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(34, 34, 34)
                        .addComponent(taAdresse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(tfCodePostal, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(tfNom, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))
                        .addGap(1, 1, 1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk_membre)
                            .addComponent(chkDonateur)
                            .addComponent(chkRevendeur)
                            .addComponent(chk_home))
                        .addGap(119, 119, 119)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkVolontaire)
                            .addComponent(chk_refuge)
                            .addComponent(chk_autre_refuge)
                            .addComponent(chk_listRouge))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jDateChooserDateViste, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(taNote, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnEnregister, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(222, 222, 222)))))
                .addGap(0, 0, 0))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {chkDonateur, chkRevendeur, chkVolontaire, chk_autre_refuge, chk_home, chk_listRouge, chk_membre, chk_refuge});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(chkVolontaire)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_autre_refuge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(chk_refuge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_listRouge)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taNote, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(chk_membre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkDonateur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkRevendeur)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_home)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserDateViste, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnregister))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(tfPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfVille, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfMail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {chkDonateur, chkRevendeur, chkVolontaire, chk_autre_refuge, chk_home, chk_listRouge, chk_membre, chk_refuge});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_listRougeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_listRougeActionPerformed
        /*est vous sur de vouloir mettre la personne dans la liste rouge ?*/

    }//GEN-LAST:event_chk_listRougeActionPerformed

    private void chk_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_homeActionPerformed
        if (chk_home.isSelected() == true) {
            taNote.setEditable(true);
        } else {
            taNote.setEditable(false);
        }
    }//GEN-LAST:event_chk_homeActionPerformed

    private void btnEnregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregisterActionPerformed
        Personne pers = new Personne(null, null, null, WIDTH, null, null, null, null, WIDTH, null, WIDTH, WIDTH, HIDE_ON_CLOSE, HIDE_ON_CLOSE, HIDE_ON_CLOSE, HIDE_ON_CLOSE, HIDE_ON_CLOSE, null);
        pers.setNom(tfNom.getText());
        pers.setPrenom(tfPrenom.getText());
        pers.setAdress(taAdresse.getText());
        pers.setCode_postal(Integer.parseInt(tfCodePostal.getText()));
        pers.setVille(tfVille.getText());
        pers.setTel(tfTelephone.getText());
        pers.setMail(tfMail.getText());
        pers.setDate_chk(jDateChooserDateViste.getDate());
        pers.setNote(taNote.getText());
        pers.setMobile(tfMobile.getText());

        /* la method getchkBox renvoir 1 ou 0*/
        pers.setCkh_home(getchkBox(chk_home.isSelected()));
        pers.setEst_autre_refuge(getchkBox(chk_autre_refuge.isSelected()));
        pers.setEst_bannie(getchkBox(chk_listRouge.isSelected()));
        pers.setEst_renvendeur(getchkBox(chkRevendeur.isSelected()));
        pers.setEst_volontaire(getchkBox(chkVolontaire.isSelected()));
        pers.setEst_autre_refuge(getchkBox(chk_autre_refuge.isSelected()));
        pers.setEst_donateur(getchkBox(chkDonateur.isSelected()));
        pers.setEst_refuge_pers(getchkBox(chk_refuge.isSelected()));

        boolean ok = daoPers.insertPersonne(pers);
        if (!ok) {
            JOptionPane.showMessageDialog(null, "Insertion impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Insertion effectuée !", null, WIDTH);
        }
        this.dispose();
    }//GEN-LAST:event_btnEnregisterActionPerformed

    private void jDateChooserDateVistePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDateVistePropertyChange
        testAllDate(jDateChooserDateViste);


    }//GEN-LAST:event_jDateChooserDateVistePropertyChange

    private void tfTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelephoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDInsertPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDInsertPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDInsertPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDInsertPersonne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDInsertPersonne dialog = new JDInsertPersonne(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregister;
    private javax.swing.JCheckBox chkDonateur;
    private javax.swing.JCheckBox chkRevendeur;
    private javax.swing.JCheckBox chkVolontaire;
    private javax.swing.JCheckBox chk_autre_refuge;
    private javax.swing.JCheckBox chk_home;
    private javax.swing.JCheckBox chk_listRouge;
    private javax.swing.JCheckBox chk_membre;
    private javax.swing.JCheckBox chk_refuge;
    private com.toedter.calendar.JDateChooser jDateChooserDateViste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private java.awt.TextArea taAdresse;
    private java.awt.TextArea taNote;
    private javax.swing.JTextField tfCodePostal;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfMobile;
    private javax.swing.JTextField tfNom;
    private javax.swing.JTextField tfPrenom;
    private javax.swing.JTextField tfTelephone;
    private javax.swing.JTextField tfVille;
    // End of variables declaration//GEN-END:variables

    private int getchkBox(boolean ok) {
        int rep;
        if (ok == true) {
            rep = 1;
        } else {
            rep = 0;
        }
        return rep;
    }
    private daoPersonne daoPers = Factory.getdaoPersonne();
    private int nbtest=0;

  
  private void testAllDate(JDateChooser chooser) {
        nbtest = nbtest+1;
        if (nbtest > 1) {
            Date now = new Date();

            if (chooser.getDate().compareTo(now) == 1) {
                JOptionPane.showMessageDialog(null, "Veuillez choisir une date valide, vous ne pouvez pas sélectionner une date future");
                chooser.setDate(now);
            }
            chk_home.setSelected(true);
            taNote.setEditable(true);
        }

    }
  
}
