/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;
//import com.l2fprod.common.swing.JDirectoryChooser;

import com.toedter.calendar.JDateChooser;
import dao.daoAnimal;
import dao.daoLieu;
import dao.daoRace;
import dao.daoType;
import factory.Factory;
import java.io.File;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import objet.Animal;
import objet.Lieu;
import objet.Race;

/**
 *
 * @author Super-Afg
 */
public class JDInsertAnimal extends javax.swing.JDialog {

    /**
     * Creates new form JDInsertAnimal
     */
    public JDInsertAnimal(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fillComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JlabelPhoto = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnInsertPhoto = new javax.swing.JButton();
        cbRace = new javax.swing.JComboBox();
        cbSexe = new javax.swing.JComboBox();
        cbTypeEspeces = new javax.swing.JComboBox();
        tfNomAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCouleur = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbTaille = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        chkBoxSterile = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfIdPuce = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbTypePuce = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cbPuce_loc = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jDateChooserNaiss = new com.toedter.calendar.JDateChooser();
        jDateChooserDateVermifuge = new com.toedter.calendar.JDateChooser();
        chkBoxDispo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        chkBoxVermifuge = new javax.swing.JCheckBox();
        jDateChooserDateSterile = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDiscription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaComportement = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbRaisonDepart = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cbRasisonEntree = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jDateChooserDepart = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jDateChooserDateEntreé = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfPersonneNom = new javax.swing.JTextField();
        tfPersonnePrenom = new javax.swing.JTextField();
        tfPersonneTel = new javax.swing.JTextField();
        tfPersonneMobile = new javax.swing.JTextField();
        tfPersonneMail = new javax.swing.JTextField();
        btnListPersonne = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaPersonneAdresse = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        tfNomVet = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfPrenomVet = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfTelephoneVet = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tfMobileVet = new javax.swing.JTextField();
        btnEnregistreVet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListVeterinaire = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaAdresseVet = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 900));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(900, 900));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 900));

        JlabelPhoto.setBackground(new java.awt.Color(255, 255, 255));
        JlabelPhoto.setIcon(new javax.swing.ImageIcon("C:\\AnimalRefuge\\image\\Autre01.png")); // NOI18N

        jLabel2.setText("Photo");

        btnInsertPhoto.setText("Inserer une photo");
        btnInsertPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPhotoActionPerformed(evt);
            }
        });

        cbRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRaceActionPerformed(evt);
            }
        });

        cbSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Femelle", "Male", "Inconnue" }));

        cbTypeEspeces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeEspecesActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom :");

        jLabel4.setText("Espéce :");

        jLabel5.setText("Race :");

        jLabel6.setText("Sexe :");

        cbCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Divers", "Noir", "Chocolat", "Lilas", "Cannelle", "Fauve", "Crème", "Noir et brun", "Noir et blanc", "Bleu", "Brun", "Brun et noir", "Brun et blanc", "Crème", "Gingembre", "Ginger et blanc", "Vert", "Gris", "Gris et blanc", "Foie", "Foie et blanc", "Tigré", "Tigré et blanc", "Bronzage", "Tan et noir", "Tan et blanc", "Tricolore", "Blanc", "Blanc et noir", "Blanc et", "Blanc et brun", "Blanc et gris", "Blanc et foie", "Blanc et tigré", "Blanc et tan", "Jaune et gris", "" }));

        jLabel7.setText("Robe :");

        cbTaille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Court", "Mi-long", "long" }));

        jLabel8.setText("Type de poil :");

        chkBoxSterile.setText("stérilisation / Castration");
        chkBoxSterile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxSterileActionPerformed(evt);
            }
        });

        jLabel9.setText("Discription :");

        jLabel10.setText("Comportement :");

        jLabel11.setText("Identification :");

        jLabel12.setText("N° identification :");

        jLabel13.setText("Type :");

        cbTypePuce.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucune", "Puce", "Tatouage" }));
        cbTypePuce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypePuceActionPerformed(evt);
            }
        });

        jLabel14.setText("Emplacement :");

        cbPuce_loc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucune", "Epaule", "Orielle" }));
        cbPuce_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPuce_locActionPerformed(evt);
            }
        });

        jLabel16.setText("Date naissance :");

        jDateChooserNaiss.setDateFormatString("dd-MM-yyyy");
        jDateChooserNaiss.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserNaissPropertyChange(evt);
            }
        });

        jDateChooserDateVermifuge.setDateFormatString("dd-MM-yyyy");
        jDateChooserDateVermifuge.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDateVermifugePropertyChange(evt);
            }
        });

        chkBoxDispo.setSelected(true);
        chkBoxDispo.setText("Disponible à l'adoption");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ajouter-en-plus-icone-9315-16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkBoxVermifuge.setText("Vermifugation");
        chkBoxVermifuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxVermifugeActionPerformed(evt);
            }
        });

        jDateChooserDateSterile.setDateFormatString("dd-MM-yyyy");
        jDateChooserDateSterile.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDateSterilePropertyChange(evt);
            }
        });

        textAreaDiscription.setColumns(20);
        textAreaDiscription.setRows(5);
        jScrollPane1.setViewportView(textAreaDiscription);

        textAreaComportement.setColumns(20);
        textAreaComportement.setRows(5);
        jScrollPane2.setViewportView(textAreaComportement);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ajouter-en-plus-icone-9315-16.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Générer un nom aléatoire");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkBoxDispo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jtfIdPuce, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cbTypePuce, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(cbPuce_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(cbTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(tfNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(129, 129, 129))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbTypeEspeces, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(cbRace, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(cbSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbCouleur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBoxVermifuge)
                            .addComponent(chkBoxSterile)
                            .addComponent(jLabel16))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserDateSterile, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDateVermifuge, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 242, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsertPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JlabelPhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JlabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInsertPhoto)
                .addGap(41, 41, 41)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTypeEspeces, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkBoxDispo)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooserNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkBoxSterile)
                                .addGap(18, 18, 18)
                                .addComponent(chkBoxVermifuge))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooserDateSterile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addComponent(jDateChooserDateVermifuge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfIdPuce, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTypePuce, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(36, 36, 36)))
                        .addGap(16, 16, 16)
                        .addComponent(jLabel14)
                        .addGap(6, 6, 6)
                        .addComponent(cbPuce_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(133, 133, 133))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jTabbedPane1.addTab("Détails sur l'animal", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 900));

        cbRaisonDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRaisonDepartActionPerformed(evt);
            }
        });

        jLabel20.setText("Localisation");

        cbRasisonEntree.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comportement", "Raison non et de Confort", "Déménagement", "Décès ou maladie du propriétaire", "Allergie", "Raison financière", "Divorce", "Naissance d un enfant", "Plainte voisinage", "Raison sociale", "Chien confié par un autre refuge", "Trouvé dans la nature", "Autres" }));

        jLabel18.setText("Raison d'arrivée :");

        jDateChooserDepart.setDateFormatString("dd-MM-yyyy");
        jDateChooserDepart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDepartPropertyChange(evt);
            }
        });

        jLabel19.setText("Date de depart :");

        jDateChooserDateEntreé.setDateFormatString("dd-MM-yyyy");
        jDateChooserDateEntreé.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserDateEntreéPropertyChange(evt);
            }
        });

        jLabel17.setText("Date d'arrivée :");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 153));
        jLabel15.setText("Apporté par  :");

        jLabel21.setText("Nom :");

        jLabel22.setText("Prenom :");

        jLabel29.setText("Adresse :");

        jLabel30.setText("Mail :");

        jLabel31.setText("Telephone");

        jLabel32.setText("Mobile :");

        tfPersonneNom.setEditable(false);

        tfPersonnePrenom.setEditable(false);

        tfPersonneTel.setEditable(false);

        tfPersonneMobile.setEditable(false);

        tfPersonneMail.setEditable(false);

        btnListPersonne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/jumelles-trouver-rechercher-zoom-icone-7070-32.png"))); // NOI18N
        btnListPersonne.setText("Rechercher");
        btnListPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPersonneActionPerformed(evt);
            }
        });

        textAreaPersonneAdresse.setEditable(false);
        textAreaPersonneAdresse.setColumns(20);
        textAreaPersonneAdresse.setRows(5);
        jScrollPane5.setViewportView(textAreaPersonneAdresse);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooserDateEntreé, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(cbRasisonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jDateChooserDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(cbRaisonDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPersonnePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfPersonneNom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListPersonne))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addGap(77, 77, 77)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel31)
                                .addComponent(jLabel32)
                                .addComponent(jLabel30))
                            .addGap(73, 73, 73)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfPersonneMail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPersonneMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPersonneTel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRasisonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDateEntreé, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRaisonDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jLabel15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(tfPersonneNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnListPersonne)))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfPersonnePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel29)
                        .addGap(121, 121, 121)
                        .addComponent(jLabel31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tfPersonneTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(tfPersonneMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tfPersonneMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(322, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfPersonneMail, tfPersonneMobile, tfPersonneNom, tfPersonnePrenom, tfPersonneTel});

        jTabbedPane1.addTab("Détails d'entrée", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(900, 900));

        tfNomVet.setEditable(false);

        jLabel23.setText("Nom :");

        tfPrenomVet.setEditable(false);

        jLabel24.setText("Prénom :");

        jLabel25.setText("Adresse :");

        tfTelephoneVet.setEditable(false);

        jLabel26.setText("Téléphone :");

        jLabel27.setText("Moblile :");

        tfMobileVet.setEditable(false);

        btnEnregistreVet.setText("Enregistrer");
        btnEnregistreVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistreVetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("le vétérinaire de l'animal :");

        btnListVeterinaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/jumelles-trouver-rechercher-zoom-icone-7070-32.png"))); // NOI18N
        btnListVeterinaire.setText("Rechercher");
        btnListVeterinaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListVeterinaireActionPerformed(evt);
            }
        });

        jTextAreaAdresseVet.setEditable(false);
        jTextAreaAdresseVet.setColumns(20);
        jTextAreaAdresseVet.setRows(5);
        jScrollPane6.setViewportView(jTextAreaAdresseVet);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEnregistreVet)
                .addGap(28, 28, 28))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTelephoneVet)
                            .addComponent(tfMobileVet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPrenomVet, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(tfNomVet, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnListVeterinaire))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {tfMobileVet, tfTelephoneVet});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfNomVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListVeterinaire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrenomVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 182, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelephoneVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMobileVet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(31, 31, 31)
                .addComponent(btnEnregistreVet)
                .addGap(32, 32, 32))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfMobileVet, tfNomVet, tfPrenomVet, tfTelephoneVet});

        jTabbedPane1.addTab("Vétérinaire", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private int donne_id_r() { /* permet de retourner id_race exemple persan,bergé,etc....*/

        int id = 0;
        ArrayList<objet.Type> TypeEsp = daoRaceType.selectTypes();
        for (int i = 0; i < TypeEsp.size(); i++) {
            if (cbTypeEspeces.getSelectedItem().toString().compareTo(TypeEsp.get(i).getNom_t()) == 0) {
                id = TypeEsp.get(i).getId_t();

            }
        }
        return id;
    }
    private void btnInsertPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPhotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        try {
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                    "JPG & GIF & PNG Images", "jpg", "gif", "png");
            chooser.setAcceptAllFileFilterUsed(false);
            chooser.setFileFilter(filter);
            chooser.setCurrentDirectory(new File("C:\\AnimalRefuge\\image"));
            chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            chooser.showOpenDialog(null);
            File selectedPfile = chooser.getSelectedFile();
            chargeImagePath(selectedPfile.getName());

        } catch (Exception e) {
        }


    }//GEN-LAST:event_btnInsertPhotoActionPerformed

    private void chkBoxSterileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxSterileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxSterileActionPerformed

    private void cbRaisonDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRaisonDepartActionPerformed
        donner_id_Lieu();
    }//GEN-LAST:event_cbRaisonDepartActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nouvnat = JOptionPane.showInputDialog(null, "Entrez une nouvelle couleur", "Insertion", JOptionPane.PLAIN_MESSAGE);

        cbCouleur.addItem(nouvnat);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkBoxVermifugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxVermifugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxVermifugeActionPerformed

    private void btnEnregistreVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistreVetActionPerformed
        Animal myAnimal = new Animal(k, null, null, null, null, null, null, null, null, null, null, WIDTH, WIDTH, null, null, null, WIDTH, null, null, null, null, k, k, WIDTH, null, null, null, WIDTH);
        myAnimal.setId_lieu(donner_id_Lieu());
        myAnimal.setId_r(donner_id_r());
        myAnimal.setId_p(idPersAnimal);
        myAnimal.setNom(tfNomAnimal.getText());
        myAnimal.setSexe(cbSexe.getSelectedItem().toString());
        myAnimal.setIdent_puce(jtfIdPuce.getText());
        myAnimal.setRace(cbTypeEspeces.getSelectedItem().toString());
        myAnimal.setEspece(cbRace.getSelectedItem().toString());
        myAnimal.setPuce_loc(cbPuce_loc.getSelectedItem().toString());
        myAnimal.setType_puce(cbTypePuce.getSelectedItem().toString());
        myAnimal.setCouleur(cbCouleur.getSelectedItem().toString());
        myAnimal.setPoil(cbTaille.getSelectedItem().toString());
        myAnimal.setSterile(getchkBox(chkBoxSterile.isSelected()));
        myAnimal.setVermifuge(getchkBox(chkBoxVermifuge.isSelected()));
        myAnimal.setDispo(getchkBox(chkBoxDispo.isSelected()));
        myAnimal.setAge(jDateChooserNaiss.getDate());
        myAnimal.setDate_entre(jDateChooserDateEntreé.getDate());
        myAnimal.setRaison(cbRasisonEntree.getSelectedItem().toString());
        myAnimal.setDate_depart(jDateChooserDepart.getDate());
        myAnimal.setRaison_depart(cbRaisonDepart.getSelectedItem().toString());
        myAnimal.setCarateristique(textAreaDiscription.getText());
        myAnimal.setDiscription(textAreaDiscription.getText());
        myAnimal.setDate_vermifuge(jDateChooserDateVermifuge.getDate());
        myAnimal.setDate_sterile(jDateChooserDateSterile.getDate());
        myAnimal.setId_vet(idVetAnimal);
        myAnimal.setPhoto(ImagePath);
        boolean ok = daoAni.insertAnimal(myAnimal);
        if (!ok) {
            JOptionPane.showMessageDialog(null, "Insertion impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Insertion effectuée !", null, WIDTH);
        }
        this.dispose();
    }//GEN-LAST:event_btnEnregistreVetActionPerformed

    private void cbTypeEspecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeEspecesActionPerformed
        k = donne_id_r();
        chargeImage(k);
        cbRace.removeAllItems();
        fillComponents2();
    }//GEN-LAST:event_cbTypeEspecesActionPerformed

    private void cbRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRaceActionPerformed
        String typeRace = (String) cbRace.getSelectedItem();
        PhotoRace(typeRace);
    }//GEN-LAST:event_cbRaceActionPerformed

    private void cbPuce_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPuce_locActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPuce_locActionPerformed

    private void btnListPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPersonneActionPerformed
        JDAffichePersonne jd = new JDAffichePersonne(null, rootPaneCheckingEnabled);
        JOptionPane.showMessageDialog(null, "Séléctionnez ou ajoutez un propriétaire", "Information", JOptionPane.INFORMATION_MESSAGE);

        jd.setVisible(true);
        try {
            idPersAnimal = jd.myPersonne.getId_p();
            tfPersonneNom.setText(jd.myPersonne.getNom());
            tfPersonnePrenom.setText(jd.myPersonne.getPrenom());
            tfPersonneMail.setText(jd.myPersonne.getMail());
            tfPersonneMobile.setText(jd.myPersonne.getMobile());
            tfPersonneTel.setText(jd.myPersonne.getTel());

            textAreaPersonneAdresse.setText(jd.myPersonne.getAdress() + "\n" + jd.myPersonne.getCode_postal() + "\n" + jd.myPersonne.getVille());

        } catch (NullPointerException e) {

        }
    }//GEN-LAST:event_btnListPersonneActionPerformed

    private void btnListVeterinaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListVeterinaireActionPerformed
        JDAfficheVeterinaire jd = new JDAfficheVeterinaire(null, rootPaneCheckingEnabled);
        JOptionPane.showMessageDialog(null, "Séléctionnez ou ajoutez un vétérinaire", "Information", JOptionPane.INFORMATION_MESSAGE);

        jd.setVisible(true);
        try {
            idVetAnimal = jd.myVeterinaire.getId_vet();
            tfNomVet.setText(jd.myVeterinaire.getNom());
            tfPrenomVet.setText(jd.myVeterinaire.getPrenom());
            tfMobileVet.setText(jd.myVeterinaire.getMobile());
            jTextAreaAdresseVet.setText(jd.myVeterinaire.getAdress() + "\n" + jd.myVeterinaire.getCode_postal() + "\n" + jd.myVeterinaire.getVille());
            tfTelephoneVet.setText(jd.myVeterinaire.getTel());
        } catch (NullPointerException e) {
        }

    }//GEN-LAST:event_btnListVeterinaireActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JDListRaceEspeces jd = new JDListRaceEspeces(null, rootPaneCheckingEnabled);
        jd.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jDateChooserDateSterilePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDateSterilePropertyChange
        testAllDate(jDateChooserDateSterile, "Date de stérilisation");
        chkBoxSterile.setSelected(true);
    }//GEN-LAST:event_jDateChooserDateSterilePropertyChange

    private void jDateChooserNaissPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserNaissPropertyChange
        testDateNais(jDateChooserNaiss.getDate());

    }//GEN-LAST:event_jDateChooserNaissPropertyChange

    private void jDateChooserDateVermifugePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDateVermifugePropertyChange
        testAllDate(jDateChooserDateVermifuge, "Date de Vermifugation");
        chkBoxVermifuge.setSelected(true);
    }//GEN-LAST:event_jDateChooserDateVermifugePropertyChange

    private void jDateChooserDateEntreéPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDateEntreéPropertyChange
        testAllDate(jDateChooserDateEntreé, "Date de d'arrivée");
    }//GEN-LAST:event_jDateChooserDateEntreéPropertyChange

    private void jDateChooserDepartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserDepartPropertyChange
        testAllDate(jDateChooserDepart, "Date de départ");
    }//GEN-LAST:event_jDateChooserDepartPropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        changeName();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbTypePuceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypePuceActionPerformed
        if (jtfIdPuce.getText().length() > 5) {
            testIdentification(jtfIdPuce.getText());
        }

    }//GEN-LAST:event_cbTypePuceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDInsertAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDInsertAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDInsertAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDInsertAnimal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDInsertAnimal dialog = new JDInsertAnimal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelPhoto;
    private javax.swing.JButton btnEnregistreVet;
    private javax.swing.JButton btnInsertPhoto;
    private javax.swing.JButton btnListPersonne;
    private javax.swing.JButton btnListVeterinaire;
    private javax.swing.JComboBox cbCouleur;
    private javax.swing.JComboBox cbPuce_loc;
    private javax.swing.JComboBox cbRace;
    private javax.swing.JComboBox cbRaisonDepart;
    private javax.swing.JComboBox cbRasisonEntree;
    private javax.swing.JComboBox cbSexe;
    private javax.swing.JComboBox cbTaille;
    private javax.swing.JComboBox cbTypeEspeces;
    private javax.swing.JComboBox cbTypePuce;
    private javax.swing.JCheckBox chkBoxDispo;
    private javax.swing.JCheckBox chkBoxSterile;
    private javax.swing.JCheckBox chkBoxVermifuge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooserDateEntreé;
    private com.toedter.calendar.JDateChooser jDateChooserDateSterile;
    private com.toedter.calendar.JDateChooser jDateChooserDateVermifuge;
    private com.toedter.calendar.JDateChooser jDateChooserDepart;
    private com.toedter.calendar.JDateChooser jDateChooserNaiss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaAdresseVet;
    private javax.swing.JTextField jtfIdPuce;
    private javax.swing.JTextArea textAreaComportement;
    private javax.swing.JTextArea textAreaDiscription;
    private javax.swing.JTextArea textAreaPersonneAdresse;
    private javax.swing.JTextField tfMobileVet;
    private javax.swing.JTextField tfNomAnimal;
    private javax.swing.JTextField tfNomVet;
    private javax.swing.JTextField tfPersonneMail;
    private javax.swing.JTextField tfPersonneMobile;
    private javax.swing.JTextField tfPersonneNom;
    private javax.swing.JTextField tfPersonnePrenom;
    private javax.swing.JTextField tfPersonneTel;
    private javax.swing.JTextField tfPrenomVet;
    private javax.swing.JTextField tfTelephoneVet;
    // End of variables declaration//GEN-END:variables

    private void fillComponents() {
        /* charger tous les TypeRace */
        ArrayList<objet.Type> TypeEsp = daoRaceType.selectTypes();
        for (int i = 0; i < TypeEsp.size(); i++) {
            cbTypeEspeces.addItem(((objet.Type) TypeEsp.get(i)).getNom_t());
        }
        /*charger tous lieu 'raison_depart'*/
        ArrayList<Lieu> ListLieu = daoLieu.selectLieu();
        for (int i = 0; i < ListLieu.size(); i++) {
            cbRaisonDepart.addItem(((Lieu) ListLieu.get(i)).getNom_l());
        }
        fillComponents2();
        getId();
    }
    /* charger toutes les Espéces */

    private void fillComponents2() {
        cbRace.removeAllItems();
        ArrayList<Race> cat = daoEspecesRace.selectRaces();
        for (int i = 0; i < cat.size(); i++) {
            if (k == cat.get(i).getId_t()) {
                cbRace.addItem(((Race) cat.get(i)).getLib_r());
            }
        }
    }
    private String ImagePath;
    protected int idVetAnimal;
    protected int idPersAnimal;
    private static int k = 1; // pour mon jcombox espece race
    private daoAnimal daoAni = Factory.getdaoAnimal();
    private daoRace daoEspecesRace = Factory.getdaoRace();
    private daoType daoRaceType = Factory.getdaoType();
    private daoLieu daoLieu = Factory.getdaoLieu();
    private int nbtest = 0;
    private int idAnimal;

    private int donner_id_r() {
        int id = 0;
        ArrayList<Race> race = daoEspecesRace.selectRaces();
        for (int i = 0; i < race.size(); i++) {
            if (cbRace.getSelectedItem().toString().compareTo(race.get(i).getLib_r()) == 0) {
                id = race.get(i).getId_r();

            }
        }
        return id;
    }

    private int donner_id_Lieu() {
        int id = 0;
        ArrayList<Lieu> ListLieu = daoLieu.selectLieu();
        for (int i = 0; i < ListLieu.size(); i++) {
            if (cbRaisonDepart.getSelectedItem().toString().compareTo(ListLieu.get(i).getNom_l()) == 0) {
                id = ListLieu.get(i).getId_l();
            }
        }
        return id;
    }

    private int getchkBox(boolean ok) {
        int rep;
        if (ok == true) {
            rep = 1;
        } else {
            rep = 0;
        }
        return rep;
    }

    /*variable necessaire pour ajouter une image*/
    private void chargeImage(int num) {
        java.util.Random rand = new java.util.Random();
        int leNombreAleatoire = rand.nextInt(4);
        String path = "C:\\AnimalRefuge\\image\\";
        String str = null;
        if (num == 1) {
            str = "chat0" + leNombreAleatoire + ".png";
        }
        if (num == 2) {
            str = "chien0" + leNombreAleatoire + ".png";
        } else {
            JlabelPhoto.setIcon(new ImageIcon(path + "Autre01.png"));
            JlabelPhoto.repaint();
        }

        if (num == 1 || num == 2) {
            switch (leNombreAleatoire) {

                case 1:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                case 2:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                case 3:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                case 4:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                default:
                    break;
            }

            ImagePath = str;
        }
    }

    private void chargeImagePath(String name) {
        String path = "C:\\AnimalRefuge\\image\\";
        if (name.compareTo("null") == 0) {
            JlabelPhoto.setIcon(new ImageIcon(path + "Autre01.png"));
            JlabelPhoto.repaint();
        } else {
            JlabelPhoto.setIcon(new ImageIcon(path + name));
            JlabelPhoto.repaint();
        }
        ImagePath = name;
    }

    private void PhotoRace(String typeRace) {
        String path = "C:\\AnimalRefuge\\image\\";
        typeRace = typeRace + ".png";

        JlabelPhoto.setIcon(new ImageIcon(path + typeRace));
        JlabelPhoto.repaint();
        ImagePath = typeRace;
    }
    /*donne id de l'animal*/

    private void getId() {
        ArrayList<Animal> an = daoAni.getIdSuivant();
        for (int i = 0; i < an.size(); i++) {
            idAnimal = an.get(i).getId_a() + 1;
        }
    }

    public static int getAge(Date birthday) {
        GregorianCalendar today = new GregorianCalendar();
        GregorianCalendar bday = new GregorianCalendar();
        GregorianCalendar bdayThisYear = new GregorianCalendar();

        bday.setTime(birthday);
        bdayThisYear.setTime(birthday);
        bdayThisYear.set(Calendar.YEAR, today.get(Calendar.YEAR));

        int age = today.get(Calendar.YEAR) - bday.get(Calendar.YEAR);

        if (today.getTimeInMillis() < bdayThisYear.getTimeInMillis()) {
            age--;
        }
        return age;
    }

    private void testDateNais(Date date) {
        nbtest = nbtest + 1;
        if (nbtest > 1) {
            int age = getAge(jDateChooserNaiss.getDate());
            Date d = new Date();
            if (age >= 30) {
                JOptionPane.showMessageDialog(null, "La date de naissance de l'animal ne pas dépasser plus 30 ans", "Erreur", JOptionPane.WARNING_MESSAGE);
                jDateChooserNaiss.setDate(d);
            }
            if (age < 0) {
                JOptionPane.showMessageDialog(null, "La date de naissance de l'animal est incorrecte", "Erreur", JOptionPane.WARNING_MESSAGE);
                jDateChooserNaiss.setDate(d);
            }
            jDateChooserDateSterile.setDate(d);
            jDateChooserDateEntreé.setDate(d);
            jDateChooserDateVermifuge.setDate(d);
            jDateChooserDepart.setDate(d);
        }
        chkBoxSterile.setSelected(false);
        chkBoxVermifuge.setSelected(false);
    }

    private void testAllDate(JDateChooser chooser, String Var) {
        Date now = new Date();
        Date age = jDateChooserNaiss.getDate();
        if (chooser.getDate().compareTo(age) != 1 || chooser.getDate().compareTo(now) == 1) {
            JOptionPane.showMessageDialog(null, Var + " est anterieure à la date naissance !", "Erreur", JOptionPane.WARNING_MESSAGE);
            chooser.setDate(now);
        }
    }

    private void changeName() {
        String[] monTableau = {"Snoopy", "Tina", "Sam", "Sally", "Ulysse", "Chipie", "Rocky", "Roxane", "Max", "Princesse", "Lady", "Oscar", "Ugo", "Tequila", "Simba", "Ramses", "Teddy", "Titus", "Maya", "Tania", "Samy", "Filou", "Tomy", "Lucky", "Junior", "Socrate", "Vanille", "Gribouille", "Choupette", "Nina", "Sandy", "Saphir", "Tara", "Lola", "Romeo", "Roxy", "Stella", "Prince", "Belle", "Tom", "Tyson", "Pacha", "Reglisse", "Scotty", "Rusty", "Caramel", "Roxanne", "Benji", "Milou", "Paco", "Sacha", "Tommy", "Caline", "Oliver", "Sultan", "Theo", "Rex", "Scott", "Nougat", "Roucky", "Samba", "Tess", "Théo", "Luna", "Nicky", "Praline", "Titeuf", "Topaze", "Enzo", "Kenzo", "Noisette", "Ruby", "Saxo", "Oceane", "Sweety", "Tessy", "Titan", "Voyou", "Charly", "Leo", "Spike", "Stan", "Suzy", "Tango", "Léo", "Perle", "Prisca", "Sissi", "Whisky", "Dolly", "Popeye", "Rita", "Taz", "Titi", "Fanny", "Felix", "Nala", "Roméo", "Toby", "Twist"};
        java.util.Random rand = new java.util.Random();
        int i = rand.nextInt(99);
        tfNomAnimal.setText(monTableau[i]);

    }

    private void testIdentification(String var) {
        ArrayList<Animal> ani = daoAni.selectAnimals();
        var = var.toUpperCase();
        for (int i = 0; i < ani.size(); i++) {
            if (var.compareTo(ani.get(i).getIdent_puce()) == 0) {
                JOptionPane.showMessageDialog(null, "Cette identifiant existe déjà");
                jtfIdPuce.setText("");
                break;
            }
        }
    }

}
