/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dao.daoAnimalSoin;
import dao.daoSoin;
import dao.daoSoinConcernMedoc;
import dao.daoType;
import dao.daoVaccin;
import dao.daoVaccination;
import dao.daoVeterinaire;
import factory.Factory;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.TableModelMedicament;
import objet.Soin;
import objet.Type_soin;
import objet.Vaccin;
import objet.Vaccination;
import objet.Veterinaire;

/**
 *
 * @author Super-Afg
 */
public class JDSoinInsert extends javax.swing.JDialog {

    /**
     * Creates new form JDVaccinInsert
     */
    public JDSoinInsert(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
        btnMedoc.setVisible(false);
        try {
            fillComponents();
        } catch (ParseException ex) {
            Logger.getLogger(JDSoinInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
        idAnimal = id;
        refresh();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDateChooserDateVaccin = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        cbVeterinaire = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        cbVaccin = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tfAreaNote = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnMedoc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAjVet = new javax.swing.JButton();
        btnAjMaladie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Date de vaccination ");

        jDateChooserDateVaccin.setDateFormatString("dd-MM-yyyy");

        jLabel3.setText("Praticien");

        cbVeterinaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVeterinaireActionPerformed(evt);
            }
        });

        jLabel4.setText("Pathologie");

        cbVaccin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVaccinActionPerformed(evt);
            }
        });

        jLabel5.setText("Observations");

        jScrollPane1.setViewportView(tfAreaNote);

        jButton1.setText("Fermer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnMedoc.setText("Médicament");
        btnMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedocActionPerformed(evt);
            }
        });

        jTable1.setModel(myTableMedoc);
        jScrollPane2.setViewportView(jTable1);

        btnAjVet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ajouter-en-plus-icone-9315-16.png"))); // NOI18N
        btnAjVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjVetActionPerformed(evt);
            }
        });

        btnAjMaladie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ajouter-en-plus-icone-9315-16.png"))); // NOI18N
        btnAjMaladie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjMaladieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbVeterinaire, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbVaccin, 0, 300, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooserDateVaccin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(75, 75, 75)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjVet)
                            .addComponent(btnAjMaladie))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMedoc)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooserDateVaccin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbVeterinaire, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(btnAjVet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbVaccin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAjMaladie, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnMedoc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVeterinaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVeterinaireActionPerformed
        if (cbVeterinaire.getSelectedIndex() != -1) {
            String selection = cbVeterinaire.getSelectedItem().toString();
            idVet = getidVet(selection);
        }

    }//GEN-LAST:event_cbVeterinaireActionPerformed

    private void cbVaccinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVaccinActionPerformed
        if (cbVaccin.getSelectedIndex() != -1) {
            String selection = cbVaccin.getSelectedItem().toString();
            idTypeSoin = getidVac(selection);
        }
    }//GEN-LAST:event_cbVaccinActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        Soin soin = new Soin(idTypeSoin, dateRappel, null, idVet, idTypeSoin, idVet);
        soin.setDate_soin(jDateChooserDateVaccin.getDate());
        soin.setNote(tfAreaNote.getText());
        soin.setId_a(idAnimal);
        soin.setId_vet(idVet);
        soin.setId_soin(idTypeSoin);
        boolean ok = daoAniSoin.insertSoin(soin);
        if (!ok) {
            JOptionPane.showMessageDialog(null, "Insertion impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Insertion effectuée !", null, WIDTH);
        }
        btnMedoc.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedocActionPerformed
        int idSoin = daoAniSoin.selectlastid();
        jdMedocConcernSoinInsert jd = new jdMedocConcernSoinInsert(null, rootPaneCheckingEnabled, idSoin);
        jd.setVisible(true);
        refresh();
    }//GEN-LAST:event_btnMedocActionPerformed

    private void btnAjVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjVetActionPerformed
        JDInsertVeterinaire jd = new JDInsertVeterinaire(null, rootPaneCheckingEnabled);
        jd.setVisible(true);
          try {
            fillComponents();
        } catch (ParseException ex) {
            Logger.getLogger(JDSoinInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAjVetActionPerformed

    private void btnAjMaladieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjMaladieActionPerformed
        JDListSoins jd = new JDListSoins(null, rootPaneCheckingEnabled);
        jd.setVisible(true);
          try {
            fillComponents();
        } catch (ParseException ex) {
            Logger.getLogger(JDSoinInsert.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAjMaladieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjMaladie;
    private javax.swing.JButton btnAjVet;
    private javax.swing.JButton btnMedoc;
    private javax.swing.JComboBox cbVaccin;
    private javax.swing.JComboBox cbVeterinaire;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooserDateVaccin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane tfAreaNote;
    // End of variables declaration//GEN-END:variables
private static daoVeterinaire daoVet = Factory.getdaoVeterinaire();
    private static daoSoin daoTypeSoin = Factory.getdaoSoin();
    private daoAnimalSoin daoAniSoin = Factory.getdaoAnimalSoin();
    private static daoVaccination daoVaccin = Factory.getdaoVaccination();
    private int idTypeSoin;
    private int idVet;
    private int idAnimal;
    private Date dateRappel;
    private daoSoinConcernMedoc daoConcern = Factory.getdaoConcernMedoc();
    private TableModelMedicament myTableMedoc = new TableModelMedicament(daoConcern.selectSoinConcernMedocPourModel(idAnimal));

    private void refresh() {
        myTableMedoc.setMyList(daoConcern.selectSoinConcernMedocPourModel(idAnimal));
    }

    private void fillComponents() throws ParseException {
        cbVaccin.removeAllItems();
        cbVeterinaire.removeAllItems();

        ArrayList<Veterinaire> vet = daoVet.selectVeterinaire();
        for (int i = 0; i < vet.size(); i++) {
            cbVeterinaire.addItem(((Veterinaire) vet.get(i)).getNom() + " " + vet.get(i).getPrenom());
        }

        ArrayList<Type_soin> vac = daoTypeSoin.selectType_soin();
        for (int i = 0; i < vac.size(); i++) {
            cbVaccin.addItem(((Type_soin) vac.get(i)).getNom_soin());
        }
        refresh();

    }

    private int getidVac(String var) {
        int retour = 0;
        ArrayList<Type_soin> tSoin = daoTypeSoin.selectType_soin();
        if (retour == 0) {
            for (int i = 0; i < tSoin.size(); i++) {
                if (tSoin.get(i).getNom_soin().compareToIgnoreCase(var) == 0) {
                    retour = tSoin.get(i).getId_soin();
                }
            }
        }

        return retour;
    }

    private int getidVet(String var) {
        int retour = 0;
        ArrayList<Veterinaire> vet = daoVet.selectVeterinaire();
        if (retour == 0) {
            for (int i = 0; i < vet.size(); i++) {
                String var2 = vet.get(i).getNom() + " " + vet.get(i).getPrenom();
                if (var2.compareToIgnoreCase(var) == 0) {
                    retour = vet.get(i).getId_vet();
                }
            }
        }

        return retour;
    }

}
