/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dao.daoVeterinaire;
import factory.Factory;
import static java.awt.image.ImageObserver.WIDTH;
import javax.swing.JOptionPane;
import objet.Veterinaire;

/**
 *
 * @author Super-Afg
 */
public class JDUpdateVeterinaire extends javax.swing.JDialog {

    /**
     * Creates new form JDInsertVeterinaire
     */
    public JDUpdateVeterinaire(java.awt.Frame parent, boolean modal, Veterinaire myVeterinaire) {
        super(parent, modal);
        initComponents();
        filComponents(myVeterinaire);
        myVet=myVeterinaire;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNomVet = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfPrenomVet = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfTelephoneVet = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tfMobileVet = new javax.swing.JTextField();
        btnEnregistreVet = new javax.swing.JButton();
        jTextAreaAdresseVet = new java.awt.TextArea();
        jLabel1 = new javax.swing.JLabel();
        tfCode_postalVet = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfVilleVet = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Vétérinaire");

        jLabel23.setText("Nom :");

        jLabel24.setText("Prénom :");

        jLabel25.setText("Adress :");

        jLabel26.setText("Téléphone :");

        jLabel27.setText("Moblile :");

        btnEnregistreVet.setText("Enregistrer");
        btnEnregistreVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistreVetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("Ajouter un vétérinaire :");

        jLabel28.setText("Code postal :");

        jLabel29.setText("Ville :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnEnregistreVet)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCode_postalVet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTelephoneVet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfMobileVet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfPrenomVet, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNomVet, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTextAreaAdresseVet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfVilleVet, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(305, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextAreaAdresseVet, tfCode_postalVet, tfMobileVet, tfNomVet, tfPrenomVet, tfTelephoneVet, tfVilleVet});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfNomVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrenomVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jTextAreaAdresseVet, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCode_postalVet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfVilleVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelephoneVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMobileVet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(64, 64, 64)
                .addComponent(btnEnregistreVet)
                .addGap(32, 32, 32))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {tfCode_postalVet, tfMobileVet, tfNomVet, tfPrenomVet, tfTelephoneVet, tfVilleVet});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnregistreVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistreVetActionPerformed
        
        myVet.setNom(tfNomVet.getText());
        myVet.setPrenom(tfPrenomVet.getText());
        myVet.setMobile(tfMobileVet.getText());
        myVet.setAdress(jTextAreaAdresseVet.getText());
        myVet.setCode_postal(Integer.parseInt(tfCode_postalVet.getText()));
        myVet.setVille(tfVilleVet.getText());
        myVet.setTel(tfTelephoneVet.getText());

        boolean ok = daoVet.updateVeterinaire(myVet);
        if (!ok) {
            JOptionPane.showMessageDialog(null, "Insertion impossible !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Insertion effectuée !", null, WIDTH);
        }
        this.dispose();
    }//GEN-LAST:event_btnEnregistreVetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnregistreVet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private java.awt.TextArea jTextAreaAdresseVet;
    private javax.swing.JTextField tfCode_postalVet;
    private javax.swing.JTextField tfMobileVet;
    private javax.swing.JTextField tfNomVet;
    private javax.swing.JTextField tfPrenomVet;
    private javax.swing.JTextField tfTelephoneVet;
    private javax.swing.JTextField tfVilleVet;
    // End of variables declaration//GEN-END:variables
 private daoVeterinaire daoVet = Factory.getdaoVeterinaire();
private Veterinaire myVet;
    private void filComponents(Veterinaire myVeterinaire) {
        tfNomVet.setText(myVeterinaire.getNom());
        tfPrenomVet.setText(myVeterinaire.getPrenom());
        tfMobileVet.setText(myVeterinaire.getMobile());
        tfTelephoneVet.setText(myVeterinaire.getTel());
        jTextAreaAdresseVet.setText(myVeterinaire.getAdress());
        tfCode_postalVet.setText("" + myVeterinaire.getCode_postal());
        tfVilleVet.setText(myVeterinaire.getVille());

    }
}
