/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 *//*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import dao.daoAnimal;
import dao.daoLieu;
import dao.daoPersonne;
import dao.daoRace;
import dao.daoSoinConcernMedoc;
import dao.daoType;
import dao.daoVaccination;
import dao.daoVeterinaire;
import factory.Factory;
import java.awt.Component;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;
import model.TableModelMedicament;
import model.TableModelVaccination;
import objet.Animal;
import objet.Lieu;
import objet.Personne;
import objet.Race;
import objet.Veterinaire;

/**
 *
 * @author Super-Afg
 */
public class JIFAfficheAnimal extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFAffichAnimal
     */
    public JIFAfficheAnimal(Animal myAnimal) {
        initComponents();
        fillComponents();
        fillComponents(myAnimal);
        monAnimal = myAnimal;
        refreshModel(myAnimal.getId_a());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        cbRace = new javax.swing.JComboBox();
        cbSexe = new javax.swing.JComboBox();
        cbTypeEspeces = new javax.swing.JComboBox();
        tfNomAnimal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbCouleur = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        cbTaille = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        chkBoxSterile = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtfIdPuce = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cbTypePuce = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cbPuce_loc = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jDateChooserNaiss = new com.toedter.calendar.JDateChooser();
        jDateChooserDateVermifuge = new com.toedter.calendar.JDateChooser();
        chkBoxDispo = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        chkBoxVermifuge = new javax.swing.JCheckBox();
        jDateChooserDateSterile = new com.toedter.calendar.JDateChooser();
        JlabelPhoto = new javax.swing.JLabel();
        btnInsertPhoto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDiscription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaComportement = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        btnNomAnimal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cbRaisonDepart = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        cbRasisonEntree = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jDateChooserDepart = new com.toedter.calendar.JDateChooser();
        jLabel19 = new javax.swing.JLabel();
        jDateChooserDateEntreé = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tfPersonneNom = new javax.swing.JTextField();
        tfPersonnePrenom = new javax.swing.JTextField();
        tfPersonneTel = new javax.swing.JTextField();
        tfPersonneMobile = new javax.swing.JTextField();
        tfPersonneMail = new javax.swing.JTextField();
        btnListPersonne = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaPersonneAdresse = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        tfNomVet = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tfPrenomVet = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        tfTelephoneVet = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tfMobileVet = new javax.swing.JTextField();
        btnEnregistreVet = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListVeterinaire = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaAdresseVet = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableVacc = new javax.swing.JTable();
        btnAjoutVacc = new javax.swing.JButton();
        btnModifierVacc = new javax.swing.JButton();
        btnSupprimerVacc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnModifMedo = new javax.swing.JButton();
        btnAjoutMedoc = new javax.swing.JButton();
        btnSupprimerMedoc = new javax.swing.JButton();
        btnEnregistrer = new javax.swing.JButton();

        setVisible(true);

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(900, 900));

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 900));

        cbRace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRaceActionPerformed(evt);
            }
        });

        cbSexe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Femelle", "Male", "Inconnue" }));

        cbTypeEspeces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTypeEspecesActionPerformed(evt);
            }
        });

        tfNomAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomAnimalActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom :");

        jLabel4.setText("Espèce :");

        jLabel5.setText("Race :");

        jLabel6.setText("Sexe :");

        cbCouleur.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Divers", "Noir", "Chocolat", "Lilas", "Cannelle", "Fauve", "Crème", "Noir et brun", "Noir et blanc", "Bleu", "Brun", "Brun et noir", "Brun et blanc", "Crème", "Gingembre", "Ginger et blanc", "Vert", "Gris", "Gris et blanc", "Foie", "Foie et blanc", "Tigré", "Tigré et blanc", "Bronzage", "Tan et noir", "Tan et blanc", "Tricolore", "Blanc", "Blanc et noir", "Blanc et", "Blanc et brun", "Blanc et gris", "Blanc et foie", "Blanc et tigré", "Blanc et tan", "Jaune et gris", "" }));

        jLabel7.setText("Robe :");

        cbTaille.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Court", "Mi-long", "long" }));

        jLabel8.setText("Type de poil :");

        chkBoxSterile.setText("Stérilisation / Castration");
        chkBoxSterile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxSterileActionPerformed(evt);
            }
        });

        jLabel9.setText("Discription :");

        jLabel10.setText("Comportement :");

        jLabel11.setText("Identification :");

        jLabel12.setText("N° identification :");

        jtfIdPuce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdPuceActionPerformed(evt);
            }
        });

        jLabel13.setText("Type :");

        cbTypePuce.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucune", "Puce", "Tatouage" }));

        jLabel14.setText("Emplacement :");

        cbPuce_loc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aucune", "Epaule", "Orielle" }));

        jLabel16.setText("Date naissance :");

        jDateChooserNaiss.setDateFormatString("dd-MM-yyyy");

        jDateChooserDateVermifuge.setDate(new java.util.Date(1393757177000L));
        jDateChooserDateVermifuge.setDateFormatString("dd-MM-yyyy");

        chkBoxDispo.setSelected(true);
        chkBoxDispo.setText("Disponible à l'adoption");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ajouter-en-plus-icone-9315-16.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        chkBoxVermifuge.setText("Vermifugation");
        chkBoxVermifuge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBoxVermifugeActionPerformed(evt);
            }
        });

        jDateChooserDateSterile.setDate(new java.util.Date(1393757177000L));
        jDateChooserDateSterile.setDateFormatString("dd-MM-yyyy");

        JlabelPhoto.setBackground(new java.awt.Color(255, 255, 255));
        JlabelPhoto.setIcon(new javax.swing.ImageIcon("C:\\AnimalRefuge\\image\\Autre01.png")); // NOI18N

        btnInsertPhoto.setText("Inserer une photo");
        btnInsertPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertPhotoActionPerformed(evt);
            }
        });

        jLabel2.setText("Photo");

        textAreaDiscription.setColumns(20);
        textAreaDiscription.setRows(5);
        jScrollPane1.setViewportView(textAreaDiscription);

        textAreaComportement.setColumns(20);
        textAreaComportement.setRows(5);
        jScrollPane2.setViewportView(textAreaComportement);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/ajouter-en-plus-icone-9315-16.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnNomAnimal.setText("Nom aléatoire");
        btnNomAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNomAnimalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel4)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cbTypeEspeces, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel5)
                                                    .addComponent(cbRace, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel7)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cbSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbCouleur, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jtfIdPuce, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(cbTypePuce, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel13)))
                                        .addGap(8, 8, 8)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(cbPuce_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(cbTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(tfNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBoxVermifuge)
                            .addComponent(chkBoxSterile)
                            .addComponent(jLabel16))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooserDateSterile, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDateVermifuge, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(chkBoxDispo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 134, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnInsertPhoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlabelPhoto, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JlabelPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnInsertPhoto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNomAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(48, 48, 48))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cbTypeEspeces, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cbRace, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(7, 7, 7)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbSexe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addComponent(chkBoxDispo)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jDateChooserNaiss, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkBoxSterile)
                                .addGap(18, 18, 18)
                                .addComponent(chkBoxVermifuge))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooserDateSterile, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addComponent(jDateChooserDateVermifuge, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtfIdPuce, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbTypePuce, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addComponent(jLabel14)
                                .addGap(6, 6, 6)
                                .addComponent(cbPuce_loc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTaille, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(133, 133, 133))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        jTabbedPane1.addTab("Détails sur l'animal", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 900));

        cbRaisonDepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRaisonDepartActionPerformed(evt);
            }
        });

        jLabel20.setText("Localisation");

        cbRasisonEntree.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Comportement", "Raison non et de Confort", "Déménagement", "Décès ou maladie du propriétaire", "Allergie", "Raison financière", "Divorce", "Naissance d un enfant", "Plainte voisinage", "Raison sociale", "Chien confié par un autre refuge", "Trouvé dans la nature", "Autres" }));

        jLabel18.setText("Raison d'arrivée :");

        jDateChooserDepart.setDateFormatString("dd-MM-yyyy");

        jLabel19.setText("Date de depart :");

        jDateChooserDateEntreé.setDate(new java.util.Date(1393757177000L));
        jDateChooserDateEntreé.setDateFormatString("dd-MM-yyyy");

        jLabel17.setText("Date d'arrivée :");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 153, 153));
        jLabel15.setText("Apporté par  :");

        jLabel21.setText("Nom :");

        jLabel22.setText("Prenom :");

        jLabel29.setText("Adresse :");

        jLabel30.setText("Mail :");

        jLabel31.setText("Telephone");

        jLabel32.setText("Mobile :");

        tfPersonneNom.setEditable(false);

        tfPersonnePrenom.setEditable(false);

        tfPersonneTel.setEditable(false);

        tfPersonneMobile.setEditable(false);
        tfPersonneMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPersonneMobileActionPerformed(evt);
            }
        });

        tfPersonneMail.setEditable(false);

        btnListPersonne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/jumelles-trouver-rechercher-zoom-icone-7070-32.png"))); // NOI18N
        btnListPersonne.setText("Rechercher");
        btnListPersonne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListPersonneActionPerformed(evt);
            }
        });

        textAreaPersonneAdresse.setEditable(false);
        textAreaPersonneAdresse.setColumns(20);
        textAreaPersonneAdresse.setRows(5);
        jScrollPane5.setViewportView(textAreaPersonneAdresse);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jDateChooserDateEntreé, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(cbRasisonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jDateChooserDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(cbRaisonDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPersonnePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfPersonneNom, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListPersonne))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addGap(77, 77, 77)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel31)
                                .addComponent(jLabel32)
                                .addComponent(jLabel30))
                            .addGap(73, 73, 73)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfPersonneMail, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPersonneMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(tfPersonneTel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRasisonEntree, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDateEntreé, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbRaisonDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooserDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36)
                .addComponent(jLabel15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel21)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPersonneNom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnListPersonne))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfPersonnePrenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(tfPersonneTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(tfPersonneMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(tfPersonneMail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Détails d'entrée", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(900, 900));

        tfNomVet.setEditable(false);

        jLabel23.setText("Nom :");

        tfPrenomVet.setEditable(false);

        jLabel24.setText("Prénom :");

        jLabel25.setText("Adresse :");

        tfTelephoneVet.setEditable(false);

        jLabel26.setText("Téléphone :");

        jLabel27.setText("Moblile :");

        tfMobileVet.setEditable(false);

        btnEnregistreVet.setText("Enregistrer");
        btnEnregistreVet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistreVetActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 153));
        jLabel1.setText("le vétérinaire de l'animal :");

        btnListVeterinaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resource/jumelles-trouver-rechercher-zoom-icone-7070-32.png"))); // NOI18N
        btnListVeterinaire.setText("Rechercher");
        btnListVeterinaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListVeterinaireActionPerformed(evt);
            }
        });

        jTextAreaAdresseVet.setEditable(false);
        jTextAreaAdresseVet.setColumns(20);
        jTextAreaAdresseVet.setRows(5);
        jScrollPane6.setViewportView(jTextAreaAdresseVet);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnregistreVet)
                .addGap(42, 42, 42))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(97, 97, 97)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfTelephoneVet, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfMobileVet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(tfNomVet, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnListVeterinaire))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tfPrenomVet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(tfNomVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListVeterinaire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrenomVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTelephoneVet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfMobileVet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addGap(43, 43, 43)
                .addComponent(btnEnregistreVet)
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Vétérinaire", jPanel3);

        jTableVacc.setModel(mytableVaccination);
        jScrollPane3.setViewportView(jTableVacc);

        btnAjoutVacc.setText("Ajouter");
        btnAjoutVacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutVaccActionPerformed(evt);
            }
        });

        btnModifierVacc.setText("Modifier");

        btnSupprimerVacc.setText("Supprimer");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAjoutVacc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnModifierVacc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupprimerVacc)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjoutVacc)
                    .addComponent(btnModifierVacc)
                    .addComponent(btnSupprimerVacc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vaccination", jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(900, 900));

        jTable2.setModel(myTableMedoc);
        jScrollPane4.setViewportView(jTable2);

        btnModifMedo.setText("Modifier");

        btnAjoutMedoc.setText("Ajouter");
        btnAjoutMedoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjoutMedocActionPerformed(evt);
            }
        });

        btnSupprimerMedoc.setText("Supprimer");

        btnEnregistrer.setText("Enregistrer");
        btnEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnregistrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnAjoutMedoc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModifMedo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSupprimerMedoc))
                            .addComponent(btnEnregistrer, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjoutMedoc)
                    .addComponent(btnModifMedo)
                    .addComponent(btnSupprimerMedoc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEnregistrer)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Les Soins", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbRaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRaceActionPerformed
        String typeRace = (String) cbRace.getSelectedItem();
        PhotoRace(typeRace);
    }//GEN-LAST:event_cbRaceActionPerformed

    private void cbTypeEspecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTypeEspecesActionPerformed
        //permet de syncroniser les jcombobox entre elle
        k = donne_id_r();
        chargeImage(k);
        cbRace.removeAllItems();
        fillComponents2();
    }//GEN-LAST:event_cbTypeEspecesActionPerformed

    private void tfNomAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomAnimalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomAnimalActionPerformed

    private void chkBoxSterileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxSterileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxSterileActionPerformed

    private void jtfIdPuceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdPuceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdPuceActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nouvnat = JOptionPane.showInputDialog(null, "Entrez une nouvelle couleur", "Insertion", JOptionPane.PLAIN_MESSAGE);

        cbCouleur.addItem(nouvnat);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkBoxVermifugeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBoxVermifugeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBoxVermifugeActionPerformed

    private void btnInsertPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertPhotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        try {
            FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "JPG & GIF & PNG Images", "jpg", "gif", "png");
        chooser.setAcceptAllFileFilterUsed(false);
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new File("C:\\AnimalRefuge\\image"));
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.showOpenDialog(null);
        File selectedPfile = chooser.getSelectedFile();

        chargeImagePath(selectedPfile.getName());
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_btnInsertPhotoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JDListRaceEspeces jd = new JDListRaceEspeces(null, rootPaneCheckingEnabled);
        jd.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cbRaisonDepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRaisonDepartActionPerformed
        donner_id_Lieu();
    }//GEN-LAST:event_cbRaisonDepartActionPerformed

    private void tfPersonneMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPersonneMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPersonneMobileActionPerformed

    private void btnListPersonneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListPersonneActionPerformed
        JDAffichePersonne jd = new JDAffichePersonne(null, rootPaneCheckingEnabled);
        JOptionPane.showMessageDialog(null, "Séléctionnez ou ajoutez un propriétaire", "Information", JOptionPane.INFORMATION_MESSAGE);
        jd.setVisible(true);
        try {
            idPersAnimal = jd.myPersonne.getId_p();
            tfPersonneNom.setText(jd.myPersonne.getNom());
            tfPersonnePrenom.setText(jd.myPersonne.getPrenom());
            tfPersonneMail.setText(jd.myPersonne.getMail());
            tfPersonneMobile.setText(jd.myPersonne.getMobile());
            tfPersonneTel.setText(jd.myPersonne.getTel());
            textAreaPersonneAdresse.setText(jd.myPersonne.getAdress() + "\n" + jd.myPersonne.getCode_postal() + "\n" + jd.myPersonne.getVille());

        } catch (NullPointerException e) {
        }
    }//GEN-LAST:event_btnListPersonneActionPerformed

    private void btnEnregistreVetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistreVetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnregistreVetActionPerformed

    private void btnListVeterinaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListVeterinaireActionPerformed
        JDAfficheVeterinaire jd = new JDAfficheVeterinaire(null, rootPaneCheckingEnabled);
        JOptionPane.showMessageDialog(null, "Séléctionnez ou ajoutez un vétérinaire", "Information", JOptionPane.INFORMATION_MESSAGE);

        jd.setVisible(true);
        try {
            System.out.println(jd.myVeterinaire.toString());
            idVetAnimal = jd.myVeterinaire.getId_vet();
            tfNomVet.setText(jd.myVeterinaire.getNom());
            tfPrenomVet.setText(jd.myVeterinaire.getPrenom());
            tfMobileVet.setText(jd.myVeterinaire.getMobile());
            jTextAreaAdresseVet.setText(jd.myVeterinaire.getAdress() + "\n" + jd.myVeterinaire.getCode_postal() + "\n" + jd.myVeterinaire.getVille());
            tfTelephoneVet.setText(jd.myVeterinaire.getTel());
        } catch (NullPointerException e) {
        }
    }//GEN-LAST:event_btnListVeterinaireActionPerformed

    private void btnEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnregistrerActionPerformed
        monAnimal.setId_lieu(donner_id_Lieu());
        monAnimal.setId_r(donner_id_r());
        monAnimal.setId_p(idPersAnimal);
        monAnimal.setId_vet(idVetAnimal);
        monAnimal.setNom(tfNomAnimal.getText());
        monAnimal.setSexe(cbSexe.getSelectedItem().toString());
        monAnimal.setIdent_puce(jtfIdPuce.getText());
        monAnimal.setRace(cbTypeEspeces.getSelectedItem().toString());
        monAnimal.setEspece(cbRace.getSelectedItem().toString());
        monAnimal.setPuce_loc(cbPuce_loc.getSelectedItem().toString());
        monAnimal.setType_puce(cbTypePuce.getSelectedItem().toString());
        monAnimal.setCouleur(cbCouleur.getSelectedItem().toString());
        monAnimal.setPoil(cbTaille.getSelectedItem().toString());
        monAnimal.setSterile(getchkBox(chkBoxSterile.isSelected()));
        monAnimal.setVermifuge(getchkBox(chkBoxVermifuge.isSelected()));
        monAnimal.setDispo(getchkBox(chkBoxDispo.isSelected()));
        monAnimal.setAge(jDateChooserNaiss.getDate());
        monAnimal.setDate_entre(jDateChooserDateEntreé.getDate());
        monAnimal.setRaison(cbRasisonEntree.getSelectedItem().toString());
        monAnimal.setDate_depart(jDateChooserDepart.getDate());
        monAnimal.setRaison_depart(cbRaisonDepart.getSelectedItem().toString());
        monAnimal.setCarateristique(textAreaDiscription.getText());
        monAnimal.setDiscription(textAreaDiscription.getText());
        monAnimal.setDate_vermifuge(jDateChooserDateVermifuge.getDate());
        monAnimal.setDate_sterile(jDateChooserDateSterile.getDate());
        monAnimal.setPhoto(ImagePath);

        //ma photo reçois le chemain de image
        // myAnimal.setPhoto(image);
        //        boolean test = true;
        //        ArrayList<Animal> Ani = daoAni.selectAnimals();
        //        for (Animal p : Ani) {
        //            int compareTo = p.getIdent_puce().compareTo(jtfIdPuce.getText());
        //            if (compareTo == 0) {
        //                JOptionPane.showMessageDialog(null, "ce code existe dèjà  !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        //                test = false;
        //            }
        //        }
        //
        //        if (test == true) {
        //Voir si l'animal existe dejè verifié la puce
        boolean ok = daoAni.updateAnimal(monAnimal);
        if (!ok) {
            JOptionPane.showMessageDialog(null, "Mise à jour échouée !", "Avertissement", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Mise à jour éffectuée avec succés !", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
        this.dispose();
    }//GEN-LAST:event_btnEnregistrerActionPerformed

    private void btnAjoutVaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutVaccActionPerformed
        JDVaccinInsert jd = new JDVaccinInsert(null, rootPaneCheckingEnabled, monAnimal.getId_a());
        jd.setVisible(true);
        refreshModel(monAnimal.getId_a());
    }//GEN-LAST:event_btnAjoutVaccActionPerformed

    private void btnAjoutMedocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjoutMedocActionPerformed
        JDSoinInsert jd = new JDSoinInsert(null, closable, idAnimal);
        jd.setVisible(true);
    }//GEN-LAST:event_btnAjoutMedocActionPerformed

    private void btnNomAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNomAnimalActionPerformed
changeName();
    }//GEN-LAST:event_btnNomAnimalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelPhoto;
    private javax.swing.JButton btnAjoutMedoc;
    private javax.swing.JButton btnAjoutVacc;
    private javax.swing.JButton btnEnregistreVet;
    private javax.swing.JButton btnEnregistrer;
    private javax.swing.JButton btnInsertPhoto;
    private javax.swing.JButton btnListPersonne;
    private javax.swing.JButton btnListVeterinaire;
    private javax.swing.JButton btnModifMedo;
    private javax.swing.JButton btnModifierVacc;
    private javax.swing.JButton btnNomAnimal;
    private javax.swing.JButton btnSupprimerMedoc;
    private javax.swing.JButton btnSupprimerVacc;
    private javax.swing.JComboBox cbCouleur;
    private javax.swing.JComboBox cbPuce_loc;
    private javax.swing.JComboBox cbRace;
    private javax.swing.JComboBox cbRaisonDepart;
    private javax.swing.JComboBox cbRasisonEntree;
    private javax.swing.JComboBox cbSexe;
    private javax.swing.JComboBox cbTaille;
    private javax.swing.JComboBox cbTypeEspeces;
    private javax.swing.JComboBox cbTypePuce;
    private javax.swing.JCheckBox chkBoxDispo;
    private javax.swing.JCheckBox chkBoxSterile;
    private javax.swing.JCheckBox chkBoxVermifuge;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooserDateEntreé;
    private com.toedter.calendar.JDateChooser jDateChooserDateSterile;
    private com.toedter.calendar.JDateChooser jDateChooserDateVermifuge;
    private com.toedter.calendar.JDateChooser jDateChooserDepart;
    private com.toedter.calendar.JDateChooser jDateChooserNaiss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableVacc;
    private javax.swing.JTextArea jTextAreaAdresseVet;
    private javax.swing.JTextField jtfIdPuce;
    private javax.swing.JTextArea textAreaComportement;
    private javax.swing.JTextArea textAreaDiscription;
    private javax.swing.JTextArea textAreaPersonneAdresse;
    private javax.swing.JTextField tfMobileVet;
    private javax.swing.JTextField tfNomAnimal;
    private javax.swing.JTextField tfNomVet;
    private javax.swing.JTextField tfPersonneMail;
    private javax.swing.JTextField tfPersonneMobile;
    private javax.swing.JTextField tfPersonneNom;
    private javax.swing.JTextField tfPersonnePrenom;
    private javax.swing.JTextField tfPersonneTel;
    private javax.swing.JTextField tfPrenomVet;
    private javax.swing.JTextField tfTelephoneVet;
    // End of variables declaration//GEN-END:variables

    private Animal monAnimal;
    private int idAnimal;
    private int idPersAnimal;   // = monAnimal.getId_p();
    private int idVetAnimal; //= monAnimal.getId_vet();
    byte[] animal_image = null;
    private static daoAnimal daoAni = Factory.getdaoAnimal();
    private static daoRace daoEspecesRace = Factory.getdaoRace();
    private static daoType daoRaceType = Factory.getdaoType();
    private static int k = 1; // pour mon jcombox espece race
    private daoLieu daoLieu = Factory.getdaoLieu();
    private daoPersonne daoPersonne = Factory.getdaoPersonne();
    private daoVeterinaire daoVeterinaire = Factory.getdaoVeterinaire();
    private daoSoinConcernMedoc daoConcern = Factory.getdaoConcernMedoc();
    private TableModelMedicament myTableMedoc = new TableModelMedicament(daoConcern.selectSoinConcernMedocPourModel(idAnimal));
    private String ImagePath;
    private daoVaccination daoVacc = Factory.getdaoVaccination();
    private TableModelVaccination mytableVaccination = new TableModelVaccination(daoVacc.selectVaccination(idAnimal));
    private String path = "C:\\AnimalRefuge\\image\\";

    private void refreshModelVaccin() {
        mytableVaccination.setMyList(daoVacc.selectVaccination(idAnimal));

    }

    protected void refreshModel(int id) {
        idAnimal = id;
        myTableMedoc.setMyList(daoConcern.selectSoinConcernMedocPourModel(idAnimal));
        resizeColumnWidth();
        refreshModelVaccin();
    }

    private void resizeColumnWidth() {
        final TableColumnModel columnModel = jTable2.getColumnModel();
        for (int column = 0; column < jTable2.getColumnCount(); column++) {
            int width = 50; // Min width
            for (int row = 0; row < jTable2.getRowCount(); row++) {
                TableCellRenderer renderer = jTable2.getCellRenderer(row, column);
                Component comp = jTable2.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width, width);
            }
            columnModel.getColumn(column).setPreferredWidth(width);
        }
        CenterText();
    }

    private void CenterText() {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable2.setDefaultRenderer(String.class, centerRenderer);
    }

    private void fillComponents(Animal myAnimal) {

        idPersAnimal = myAnimal.getId_p();
        idVetAnimal = myAnimal.getId_vet();
        tfNomAnimal.setText(myAnimal.getNom());
        jtfIdPuce.setText(myAnimal.getIdent_puce());
        textAreaComportement.setText(myAnimal.getCarateristique());
        textAreaDiscription.setText(myAnimal.getDiscription());
        getComboIndex(cbCouleur, myAnimal.getCouleur());
        getComboIndex(cbRaisonDepart, myAnimal.getRaison_depart());
        getComboIndex(cbRasisonEntree, myAnimal.getRaison());
        getComboIndex(cbSexe, myAnimal.getSexe());

        getComboIndex(cbTaille, myAnimal.getPoil());
        getComboIndex(cbTypePuce, myAnimal.getType_puce());
        getComboIndex(cbPuce_loc, myAnimal.getPuce_loc());
        getComboIndex(cbTypeEspeces, myAnimal.getRace());
        getComboIndex(cbRace, myAnimal.getEspece());
        ImagePath = myAnimal.getPhoto();
        chargeImagePath(ImagePath);
        jDateChooserDateEntreé.setDate(myAnimal.getDate_entre());
        jDateChooserDateSterile.setDate(myAnimal.getDate_sterile());
        jDateChooserDateVermifuge.setDate(myAnimal.getDate_vermifuge());
        jDateChooserDepart.setDate(myAnimal.getDate_depart());
        jDateChooserNaiss.setDate(myAnimal.getAge());

        //permet de selection le chekbox quand il le faut 
        chkBoxDispo.setSelected(getchkBoxSelect(myAnimal.getDispo()));
        chkBoxSterile.setSelected(getchkBoxSelect(myAnimal.getSterile()));
        chkBoxVermifuge.setSelected(getchkBoxSelect(myAnimal.getVermifuge()));
        //permet de charger la cordonné de la personne qui apporter l'animal
        chargePersonne(myAnimal.getId_p());
        chargeVeterinaire(myAnimal.getId_vet());
        //permet de se positoner sur l'index 'Adopter' import
        if (myAnimal.getId_lieu() == 5) {
            getComboIndex(cbRaisonDepart, "Adopter");
        }

    }

    //methode qui permet de reçevoir mes cb box selection sur le bon elements
    private void getComboIndex(JComboBox cb, String element) {

        for (int i = 0; i < cb.getItemCount(); i++) {//Combo étant ton JComboBox 
            if (cb.getItemAt(i).toString().compareTo(element) == 0) {

                cb.setSelectedIndex(i);
                break;
            }

        }

    }

    private int donne_id_r() { /* permet de retourner id_race exemple persan,bergé,etc....*/

        int id = 0;
        ArrayList<objet.Type> TypeEsp = daoRaceType.selectTypes();
        for (int i = 0; i < TypeEsp.size(); i++) {
            if (cbTypeEspeces.getSelectedItem().toString().compareTo(TypeEsp.get(i).getNom_t()) == 0) {
                id = TypeEsp.get(i).getId_t();

            }
        }
        return id;
    }

    private int donner_id_Lieu() {
        int id = 0;
        ArrayList<Lieu> ListLieu = daoLieu.selectLieu();
        for (int i = 0; i < ListLieu.size(); i++) {
            if (cbRaisonDepart.getSelectedItem().toString().compareTo(ListLieu.get(i).getNom_l()) == 0) {
                id = ListLieu.get(i).getId_l();
            }
        }
        return id;
    }

    private void fillComponents() {

        /* charger tous les TypeRace */
        ArrayList<objet.Type> TypeEsp = daoRaceType.selectTypes();
        for (int i = 0; i < TypeEsp.size(); i++) {
            cbTypeEspeces.addItem(((objet.Type) TypeEsp.get(i)).getNom_t());
        }
        /*charger tous lieu 'raison_depart'*/
        ArrayList<Lieu> ListLieu = daoLieu.selectLieu();
        for (int i = 0; i < ListLieu.size(); i++) {
            cbRaisonDepart.addItem(((Lieu) ListLieu.get(i)).getNom_l());
        }
        ArrayList<Race> cat = daoEspecesRace.selectRaces();
        for (int i = 0; i < cat.size(); i++) {
            cbRace.addItem(((Race) cat.get(i)).getLib_r());
        }

    }
    /* charger toutes les Espéces */

    private void fillComponents2() {
        ArrayList<Race> cat = daoEspecesRace.selectRaces();
        for (int i = 0; i < cat.size(); i++) {
            if (k == cat.get(i).getId_t()) {
                cbRace.addItem(((Race) cat.get(i)).getLib_r());
            }
        }
        chargeImage(k);
    }

    private int donner_id_r() {
        int id = 0;
        ArrayList<Race> race = daoEspecesRace.selectRaces();
        for (int i = 0; i < race.size(); i++) {
            if (cbRace.getSelectedItem().toString().compareTo(race.get(i).getLib_r()) == 0) {
                id = race.get(i).getId_r();
            }
        }
        return id;
    }

    private int getchkBox(boolean ok) {
        int rep;
        if (ok == true) {
            rep = 1;
        } else {
            rep = 0;
        }
        return rep;
    }

    private boolean getchkBoxSelect(int select) {
        boolean rep;
        if (select == 1) {
            rep = true;
        } else {
            rep = false;
        }
        return rep;
    }

    private void chargePersonne(int id) {
        ArrayList<Personne> myPersonnes = daoPersonne.selectPersonne();
        for (int i = 0; i < myPersonnes.size(); i++) {
            if (myPersonnes.get(i).getId_p() == id) {
                tfPersonneNom.setText(myPersonnes.get(i).getNom());
                tfPersonnePrenom.setText(myPersonnes.get(i).getPrenom());
                tfPersonneMail.setText(myPersonnes.get(i).getMail());
                tfPersonneTel.setText(myPersonnes.get(i).getTel());
                tfPersonneMobile.setText(myPersonnes.get(i).getMobile());
                textAreaPersonneAdresse.setText(myPersonnes.get(i).getAdress() + "\n" + myPersonnes.get(i).getCode_postal() + "\n" + myPersonnes.get(i).getVille());
            }
        }
    }

    private void chargeVeterinaire(int id) {
        ArrayList<Veterinaire> myVeterinaire = daoVeterinaire.selectVeterinaire();
        for (int i = 0; i < myVeterinaire.size(); i++) {
            if (myVeterinaire.get(i).getId_vet() == id) {
                tfNomVet.setText(myVeterinaire.get(i).getNom());
                tfPrenomVet.setText(myVeterinaire.get(i).getPrenom());
                tfMobileVet.setText(myVeterinaire.get(i).getMobile());
                tfTelephoneVet.setText(myVeterinaire.get(i).getTel());
                jTextAreaAdresseVet.setText(myVeterinaire.get(i).getAdress() + "\n" + myVeterinaire.get(i).getCode_postal() + "\n" + myVeterinaire.get(i).getVille());

            }
        }
    }

    private void chargeImage(int num) {
        java.util.Random rand = new java.util.Random();
        int leNombreAleatoire = rand.nextInt(4);

        String str = null;
        if (num == 1) {
            str = "chat0" + leNombreAleatoire + ".png";
        }
        if (num == 2) {
            str = "chien0" + leNombreAleatoire + ".png";
        } else {
            JlabelPhoto.setIcon(new ImageIcon(path + "Autre01.png"));
            JlabelPhoto.repaint();
        }

        if (num == 1 || num == 2) {
            switch (leNombreAleatoire) {

                case 1:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                case 2:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                case 3:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                case 4:
                    JlabelPhoto.setIcon(new ImageIcon(path + str));
                    JlabelPhoto.repaint();
                    break;
                default:
                    break;
            }

            ImagePath = str;
        }
    }

    private void chargeImagePath(String name) {

        if (name.compareTo("null") == 0) {
            name = "Autre01.png";
            JlabelPhoto.setIcon(new ImageIcon(path + name));
            JlabelPhoto.repaint();
        } else {
            JlabelPhoto.setIcon(new ImageIcon(path + name));
            JlabelPhoto.repaint();
        }
        ImagePath = name;
    }

    private void PhotoRace(String typeRace) {

        typeRace = typeRace + ".png";
        JlabelPhoto.setIcon(new ImageIcon(path + typeRace));
        JlabelPhoto.repaint();
        ImagePath = typeRace;
    }
      private void changeName() {
        String[] monTableau = {"Snoopy", "Tina", "Sam", "Sally", "Ulysse", "Chipie", "Rocky", "Roxane", "Max", "Princesse", "Lady", "Oscar", "Ugo", "Tequila", "Simba", "Ramses", "Teddy", "Titus", "Maya", "Tania", "Samy", "Filou", "Tomy", "Lucky", "Junior", "Socrate", "Vanille", "Gribouille", "Choupette", "Nina", "Sandy", "Saphir", "Tara", "Lola", "Romeo", "Roxy", "Stella", "Prince", "Belle", "Tom", "Tyson", "Pacha", "Reglisse", "Scotty", "Rusty", "Caramel", "Roxanne", "Benji", "Milou", "Paco", "Sacha", "Tommy", "Caline", "Oliver", "Sultan", "Theo", "Rex", "Scott", "Nougat", "Roucky", "Samba", "Tess", "Théo", "Luna", "Nicky", "Praline", "Titeuf", "Topaze", "Enzo", "Kenzo", "Noisette", "Ruby", "Saxo", "Oceane", "Sweety", "Tessy", "Titan", "Voyou", "Charly", "Leo", "Spike", "Stan", "Suzy", "Tango", "Léo", "Perle", "Prisca", "Sissi", "Whisky", "Dolly", "Popeye", "Rita", "Taz", "Titi", "Fanny", "Felix", "Nala", "Roméo", "Toby", "Twist"};
        java.util.Random rand = new java.util.Random();
        int i = rand.nextInt(99);
        tfNomAnimal.setText(monTableau[i]);
        
    }

}
